### ISSUE TITLE
Download file with long filename failing

### ISSUE THREAD

**Issue by BinyaminSchein** [boto/botocore#1916]
using aws cli to download file i get the following error:
download failed: s3://mybucket/12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg to ./12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg [Errno 36] File name too long: u'/12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg.fF65b5e9'

getconf NAME_MAX / return 255

The filename is less then the os limit but with the suffix that boto adds on it is too long for the OS and fails.
A similar problem occurred in this issue: https://github.com/aws/aws-cli/issues/2983 and was solved in this MR https://github.com/boto/botocore/pull/1322

**Comment by swetashre** [comment]
@BinyaminSchein - Thank you for your post. Can you please provide me with full debug logs ? You can enable log by adding ```boto3.set_stream_logger('')``` to your code.

**Comment by swetashre** [comment]
I am able to reproduce this issue. Marking this as bug.

**Comment by swetashre** [comment]
Closing the issue as the it has been resolved with the closing of the PR.

**Comment by TheNavigat** [comment]
This is still happening for me.

Here are the exact commands I use:

```
$ aws s3 cp s3://bucket-name/dirname dirname --recursive
download failed: s3://bucket-name/dir-name/12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg to dir-name/12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg [Errno 36] File name too long: '/home/nav/dir-name/12345678101214161820222426283032343638404244464850525456586062646687072747678808284868890929496981011041071101131161191221251281234567810121416182022242628303234363840424446485052545658606264668707274767880828486889092949698101104107110113116119122.jpg.8C2e65Fa'
```

I replaced the real filename with the jpg filename above though.

**Comment by cynepco3hahue** [comment]
Hi folks, the issue is still relevant for filenames that includes characters that took more than one byte because limitation of most filesystems is on size of filename in bytes and not on filename length.
For example, the code succeeds to download files with the name:
```
file_name = 255 * 'a'
```
but failed to download file with the name:
```
file_name = 255 * 'א'
```
The real check under the code should be something like
```
len(s.encode('utf-8')) < _MAX_FILENAME_LEN
```

**Comment by cynepco3hahue** [comment]
@swetashre Can you please re-open the issue

**Comment by tim-finnigan** [comment]
@cynepco3hahue which OS are you using? Can you provide the reproduction steps?

In [s3transfer](https://github.com/boto/s3transfer/blob/1eef558b3f6e8e8f6da1e45721147b738dd12297/s3transfer/utils.py#L244) the limit is set as `_MAX_FILENAME_LEN = 255`. 

This works for me:
```python3
import boto3

client = boto3.client('s3')

file_name = 255 * 'א'
f = open(file_name, 'w')
f.close()

client.upload_file(file_name, 'bucket', file_name)
client.download_file('bucket', file_name, file_name)
```
(And adding any more characters to the download file name results in `OSError: [Errno 63] File name too long: ...` which I would expect.)

---

For context on key name length from the [S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html): 
> "The object key name is a sequence of Unicode characters with UTF-8 encoding of up to 1,024 bytes long."

**Comment by cynepco3hahue** [comment]
@tim-finnigan Thanks for quick answer, the problem is happening for me on CentOS7, the same is working just fine on MacOS(it is depending on underlying filesystem).
For example you can easily see it via example
```
>>> test_file_name = 255 * 'א'
>>> with open(test_file_name, 'wb') as f:
...     f.write(b'Hello world')
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 36] File name too long: 'אאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאאא'
```

**Comment by cynepco3hahue** [comment]
AFAIK, most linux related FS are having limit of 255 bytes for filename. When MacOS FS has limit of 255 UTF-16 chars.

**Comment by cynepco3hahue** [comment]
I unsure what the correct way to solve it, because now you can not really cut some characters by length(for UTF-8 it possible that character will have size 1, 2, 3 or 4 bytes), it think it possible to generate some hash instead of filename and use it as temp file instead of adding suffix to original filename. But we should be sure that generated has has minimal possibility for collision :(

**Comment by tim-finnigan** [comment]
Thanks for following up and sharing that info. I think it's worth reopening this issue for tracking and more discussion. I'm also not sure on how to address this but would like to hear from others.
