### ISSUE TITLE
Add support for urllib3 2.2.1

### ISSUE THREAD

**Issue by brodybits** [boto/botocore#3138]
### Describe the bug

Underlying `botocore` requires outdated `urllib3` version:

- 1.x in case of Python pre-3.10
- < 2.1 in case of Python 3.10(+)

background from: https://github.com/boto/botocore/issues/2926

I do totally understand the motivation for these outdated `urllib3` version dependencies. IMHO I think it should be up to whoever uses boto3 to specify whether or not to use an outdated version of `urllib3`.

Incidentally I am using this for an application that may run on Amazon Linux, which may need the older `urllib3` dependency, would have preferred to make this choice myself.

I am taking liberty to file this issue for `boto3`, no objections if maintainers want to transfer this to `botocore`.

I am also taking liberty to leave out some info that I think should not matter - please post a loud holler if any further info is needed. Thanks in advance!

### Expected Behavior

I think it should be possible to install boto3 and another package such as requests with recently updated version of urllib3 such as `urllib3 == 2.2.1`.

### Current Behavior

Combinaiton of `boto3 == 1.34.46` & `urllib3 == 2.2.1` leads to pip installation error.

### Reproduction Steps

see above - please post a loud holler if any further info is needed

### SDK version used

Python 3.9 / 3.11; boto3 v1.34.46

### Environment details (OS name and version, etc.)

Ubuntu 22.04.3 LTS 64-bit (with some customized updates) on Intel core i7

**Comment by robd003** [comment]
Why not have botocore 1.x for ancient Python versions and botocore 2.x for all the modern cool kids who stick with active stable releases and actually maintain their code base?

**Comment by nateprewitt** [comment]
Thanks for the feedback, @robd003. To make sure we're on the same page, all versions of urllib3 we support are actively maintained, stable releases. urllib3 1.x is still receiving updates and we're currently ~3 weeks behind on the first stable release of urllib3 for 2.x beyond what we currently support.

Major versioning botocore would make this packaging problem considerably worse. Anyone using the AWSCLI, PynamoDB, Boto3, aiobotocore, or s3fs in conjunction would start breaking with a new major version and you'd still have a urllib3 pin somewhere in that set. We'd also be detracting time from fixing this issue in the current major version of botocore by having to maintain multiple variants of this package. There's no tangible benefit to the end user in that setup.

Thanks for your continued patience while this is addressed.

**Comment by nateprewitt** [comment]
To follow up, this was resolved in today's release (botocore 1.34.63) with #3141. Users on Python 3.10+ should be free to control their urllib3 2.x requirements going forward.

**Comment by annieDang** [comment]
Still happens `botocore 1.34.63 depends on urllib3<1.27 and >=1.25.4; python_version < "3.10"`
